version: '3.8'

services:
  web:
    platform: linux/amd64
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - nginx

  nginx:
    platform: linux/amd64
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"

volumes:
  static_volume:
