# Generated by Django 4.2.3 on 2023-08-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_qna_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='mbti',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
