# Generated by Django 4.2.3 on 2023-08-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
